use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Unique identifier for an agent instance.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AgentId(pub String);

impl AgentId {
    pub fn new(id: &str) -> Self { Self(id.to_string()) }
    pub fn generate() -> Self {
        Self(format!("agent-{}", Uuid::new_v4()))
    }
}

impl std::fmt::Display for AgentId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// The type/category of a task.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[derive(Default)]
pub enum AgentType {
    Research,
    Coding,
    Implementation,
    #[default]
    General,
}

impl<'de> Deserialize<'de> for AgentType {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "research" => Ok(AgentType::Research),
            "coding" => Ok(AgentType::Coding),
            "implementation" => Ok(AgentType::Implementation),
            "general" => Ok(AgentType::General),
            _ => Err(serde::de::Error::custom(format!(
                "unknown agent type: {}",
                s
            ))),
        }
    }
}


impl std::fmt::Display for AgentType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AgentType::Research => write!(f, "research"),
            AgentType::Coding => write!(f, "coding"),
            AgentType::Implementation => write!(f, "implementation"),
            AgentType::General => write!(f, "general"),
        }
    }
}

/// A single unit of work within an execution plan.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Task {
    /// Unique identifier for this task.
    pub id: String,
    /// Human-readable description of what this task does.
    pub description: String,
    /// Agent type best suited for this task.
    pub agent_type: AgentType,
    /// Input data required to execute this task (tool parameters, context, etc.).
    pub input: serde_json::Value,
    /// Optional parent task ID — if set, this task depends on the parent completing first.
    /// Accepts a single string or an array of strings in JSON; stored as the first element.
    #[serde(deserialize_with = "deserialize_depends_on", default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<String>,
    /// Maximum number of retry attempts before marking as failed.
    #[serde(default = "default_max_retries")]
    pub max_retries: u32,
    /// Priority ordering (lower number = higher priority).
    #[serde(default = "default_priority")]
    pub priority: u32,
    /// Arbitrary metadata (e.g., invocation source, handoff info).
    #[serde(default)]
    pub metadata: serde_json::Value,
}

fn deserialize_depends_on<'de, D>(deserializer: D) -> Result<Option<String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = serde_json::Value::deserialize(deserializer)?;
    match value {
        serde_json::Value::Null => Ok(None),
        serde_json::Value::String(s) => Ok(Some(s)),
        serde_json::Value::Array(arr) if !arr.is_empty() => {
            if let Some(serde_json::Value::String(first)) = arr.first() {
                Ok(Some(first.clone()))
            } else {
                Err(serde::de::Error::custom("depends_on array must contain strings"))
            }
        }
        serde_json::Value::Array(_) => Ok(None),
        _ => Err(serde::de::Error::custom("depends_on must be a string, array of strings, or null")),
    }
}

fn default_max_retries() -> u32 { 3 }
fn default_priority() -> u32 { 0 }

impl Task {
    pub fn new(description: &str, agent_type: AgentType, input: serde_json::Value) -> Self {
        Self {
            id: format!("task-{}", Uuid::new_v4()),
            description: description.to_string(),
            agent_type,
            input,
            depends_on: None,
            max_retries: default_max_retries(),
            priority: default_priority(),
            metadata: serde_json::Value::Object(serde_json::Map::new()),
        }
    }
}

/// A complete plan generated by the Planner and executed by the Supervisor.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ExecutionPlan {
    /// Unique plan identifier.
    pub plan_id: String,
    /// The original user request that this plan addresses.
    pub user_request: String,
    /// All tasks to be executed.
    pub tasks: Vec<Task>,
    /// Timestamp when the plan was created. Defaults to current time if omitted.
    #[serde(default = "chrono::Utc::now")]
    pub created_at: DateTime<Utc>,
    /// Arbitrary metadata (e.g., confidence score, estimated steps).
    #[serde(default)]
    pub metadata: serde_json::Value,
}

impl ExecutionPlan {
    pub fn new(user_request: &str, tasks: Vec<Task>) -> Self {
        Self {
            plan_id: format!("plan-{}", Uuid::new_v4()),
            user_request: user_request.to_string(),
            tasks,
            created_at: Utc::now(),
            metadata: serde_json::Value::Object(serde_json::Map::new()),
        }
    }

    /// Returns tasks in dependency-respecting, priority-ordered sequence.
    ///
    /// Every task is emitted only after all of its (transitive) dependencies.
    /// A dependency that references a missing task id is ignored (treated as
    /// already satisfied). A dependency *cycle* is broken deterministically:
    /// the first task encountered in the cycle is emitted before its
    /// dependencies so the pipeline can proceed rather than deadlock.
    pub fn ordered_tasks(&self) -> Vec<&Task> {
        let mut sorted = Vec::new();
        let mut visited: std::collections::HashSet<&str> = std::collections::HashSet::new();
        let mut in_stack: std::collections::HashSet<&str> = std::collections::HashSet::new();

        fn visit<'a>(
            task: &'a Task,
            all_tasks: &'a [Task],
            visited: &mut std::collections::HashSet<&'a str>,
            in_stack: &mut std::collections::HashSet<&'a str>,
            sorted: &mut Vec<&'a Task>,
        ) {
            let id: &'a str = &task.id;
            if visited.contains(id) {
                return;
            }
            // Cycle detected: this task is already on the current recursion
            // path. Break the cycle by emitting it now. Mark it `visited`
            // FIRST so the outer recursion frame (which is about to resume and
            // push the same task) sees it as already emitted and skips it —
            // otherwise the task would be emitted twice.
            if in_stack.contains(id) {
                tracing::warn!(
                    "ordered_tasks: dependency cycle detected at task '{}'; breaking it",
                    task.id
                );
                visited.insert(id);
                in_stack.remove(id);
                sorted.push(task);
                return;
            }

            in_stack.insert(id);
            if let Some(dep_id) = &task.depends_on {
                if let Some(dep) = all_tasks.iter().find(|t| t.id == *dep_id) {
                    visit(dep, all_tasks, visited, in_stack, sorted);
                }
                // A dependency on a missing task id is ignored.
            }
            in_stack.remove(id);
            // Re-check: a dependency cycle may have caused this exact task to
            // be emitted already while resolving a deeper frame. If so, do not
            // emit it a second time.
            if visited.contains(id) {
                return;
            }
            visited.insert(id);
            sorted.push(task);
        }

        // Seed from roots (no dependencies), highest priority first.
        let mut roots: Vec<&Task> = self
            .tasks
            .iter()
            .filter(|t| t.depends_on.is_none())
            .collect();
        roots.sort_by_key(|t| t.priority);
        for root in roots {
            visit(root, &self.tasks, &mut visited, &mut in_stack, &mut sorted);
        }

        // Sweep any remaining tasks (e.g., members of a cycle that was never
        // seeded from a root). Recurse so their dependencies are ordered too,
        // instead of appending them in raw plan order (C2).
        for task in &self.tasks {
            let id: &str = &task.id;
            if !visited.contains(id) {
                visit(task, &self.tasks, &mut visited, &mut in_stack, &mut sorted);
            }
        }

        sorted
    }

    /// Returns the set of root tasks (no dependencies).
    pub fn root_tasks(&self) -> Vec<&Task> {
        let dep_set: std::collections::HashSet<&str> = self
            .tasks
            .iter()
            .filter_map(|t| t.depends_on.as_deref())
            .collect();
        self.tasks
            .iter()
            .filter(|t| !dep_set.contains(t.id.as_str()))
            .collect()
    }
}

/// The result returned by a Worker Agent after executing a task.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AgentResult {
    pub task_id: String,
    pub agent_id: String,
    pub agent_type: AgentType,
    pub status: TaskStatus,
    /// The output payload (success data, error message, or partial result).
    pub output: serde_json::Value,
    /// Human-readable summary for the feedback loop.
    #[serde(default)]
    pub summary: String,
    /// Whether the Supervisor should ask the Planner to refine the plan.
    #[serde(default)]
    pub needs_refinement: bool,
    /// Whether the error is fixable by the planner (e.g., missing tool parameters).
    #[serde(default)]
    pub fixable: bool,
    /// Follow-up tasks the worker suggests adding.
    #[serde(default)]
    pub suggested_followup: Vec<Task>,
    /// Timing information.
    #[serde(default)]
    pub duration_ms: u64,
    #[serde(default)]
    pub completed_at: Option<DateTime<Utc>>,
}

/// Metadata about an agent for discovery.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AgentMetadata {
    /// Unique name of the agent.
    pub name: String,
    /// Human-readable description.
    pub description: String,
    /// The agent type.
    pub agent_type: AgentType,
    /// Tool names this agent is authorized to use.
    pub allowed_tools: Vec<String>,
}

/// Parameters for invoking another agent via the agent_call tool.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AgentCallParams {
    /// Name of the target agent to invoke.
    pub target: String,
    /// Description of the sub-task to execute.
    pub task: String,
    /// Input parameters for the sub-task.
    #[serde(default)]
    pub input: serde_json::Value,
}

impl AgentCallParams {
    /// Convert to a Task that can be executed by the target agent.
    pub fn to_task(&self, source_agent_id: &str) -> Task {
        Task {
            id: format!("handoff-{}-{}", source_agent_id, Uuid::new_v4()),
            description: self.task.clone(),
            agent_type: AgentType::General,
            input: self.input.clone(),
            depends_on: None,
            max_retries: 1,
            priority: 0,
            metadata: serde_json::json!({ "invoked_by": source_agent_id }),
        }
    }
}

/// Task execution status.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TaskStatus {
    Pending,
    Running,
    Completed,
    Failed,
    Retryable,
    Cancelled,
}

impl std::fmt::Display for TaskStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TaskStatus::Pending => write!(f, "pending"),
            TaskStatus::Running => write!(f, "running"),
            TaskStatus::Completed => write!(f, "completed"),
            TaskStatus::Failed => write!(f, "failed"),
            TaskStatus::Retryable => write!(f, "retryable"),
            TaskStatus::Cancelled => write!(f, "cancelled"),
        }
    }
}

/// Messages that flow between agents in the feedback loop.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum FeedbackMessage {
    /// Worker reports completion or failure to Supervisor.
    TaskReport { result: AgentResult },
    /// Supervisor asks Planner to refine the plan.
    RequestRefinement {
        completed_tasks: Vec<AgentResult>,
        failed_tasks: Vec<AgentResult>,
        context: serde_json::Value,
    },
    /// Planner returns an updated plan.
    UpdatedPlan { plan: ExecutionPlan },
    /// Supervisor delegates a task to a Worker.
    TaskDelegation { task: Task, context: serde_json::Value },
    /// Planner signals that the overall objective is satisfied.
    ObjectiveComplete { final_output: serde_json::Value },
}

/// Builds a context value from completed task results, keyed by task_id.
///
/// M3: only `Completed` results are included. Including `Failed` results would
/// leak error payloads into the parent context that downstream tasks consume.
pub fn build_context(completed: &[AgentResult]) -> serde_json::Value {
    let mut map = serde_json::Map::new();
    for result in completed {
        if result.status == TaskStatus::Completed {
            map.insert(result.task_id.clone(), result.output.clone());
        }
    }
    serde_json::Value::Object(map)
}

/// Looks up a parent task's output from the context.
pub fn get_parent_output<'a>(context: &'a serde_json::Value, task_id: &str) -> Option<&'a serde_json::Value> {
    context.get(task_id)
}

/// Merges parent task outputs from context into a task's input.
pub fn merge_context_into_input(
    input: &serde_json::Value,
    context: &serde_json::Value,
    depends_on: &Option<String>,
) -> serde_json::Value {
    if let Some(dep_id) = depends_on {
        if let Some(parent_output) = context.get(dep_id) {
            let mut merged = input.clone();
            if let serde_json::Value::Object(mut obj) = merged {
                if let serde_json::Value::Object(parent_obj) = parent_output {
                    for (k, v) in parent_obj {
                        obj.entry(k.clone()).or_insert(v.clone());
                    }
                }
                merged = serde_json::Value::Object(obj);
            }
            merged
        } else {
            input.clone()
        }
    } else {
        input.clone()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_agent_id_generate() {
        let id1 = AgentId::generate();
        let id2 = AgentId::generate();
        assert_ne!(id1, id2);
        assert!(id1.0.starts_with("agent-"));
    }

    #[test]
    fn test_task_new() {
        let task = Task::new("test task", AgentType::General, serde_json::json!({ "query": "hello" }));
        assert_eq!(task.description, "test task");
        assert_eq!(task.agent_type, AgentType::General);
        assert_eq!(task.max_retries, 3);
        assert_eq!(task.priority, 0);
    }

    #[test]
    fn test_execution_plan_ordered_tasks() {
        let t1 = Task::new("first", AgentType::General, serde_json::json!({}));
        let t2 = Task::new("second", AgentType::General, serde_json::json!({}));
        let t3 = Task::new("third (depends on first)", AgentType::Coding, serde_json::json!({})) ;
        let mut plan = ExecutionPlan::new("test", vec![t2, t1.clone(), t3.clone()]);
        let t1_id = t1.id.clone();
        let t3_id = t3.id.clone();
        // Set up dependency: t3 depends on t1
        if let Some(task) = plan.tasks.iter_mut().find(|t| t.id == t3_id) {
            task.depends_on = Some(t1_id.clone());
        }
        let ordered = plan.ordered_tasks();
        let ids: Vec<&str> = ordered.iter().map(|t| &t.id[..8]).collect();
        // t1 should come before t3
        let t1_idx = ordered.iter().position(|t| t.id == t1_id).unwrap();
        let t3_idx = ordered.iter().position(|t| t.id == t3_id).unwrap();
        assert!(t1_idx < t3_idx, "dependency t1 should come before t3");
    }

    /// C2: a dependency chain that is never seeded from a root must still be
    /// emitted in dependency order (the old code appended such tasks in raw
    /// plan order, violating their dependencies).
    #[test]
    fn test_ordered_tasks_isolated_chain() {
        // d1 <- d2 <- d3, none of them a root in raw order, d3 listed first.
        let d1 = Task::new("d1", AgentType::General, serde_json::json!({}));
        let d2 = Task::new("d2", AgentType::General, serde_json::json!({}));
        let d3 = Task::new("d3", AgentType::General, serde_json::json!({}));
        let d1_id = d1.id.clone();
        let d2_id = d2.id.clone();
        let d3_id = d3.id.clone();
        let mut plan = ExecutionPlan::new("chain", vec![d3, d2, d1]);
        if let Some(t) = plan.tasks.iter_mut().find(|t| t.id == d2_id) {
            t.depends_on = Some(d1_id.clone());
        }
        if let Some(t) = plan.tasks.iter_mut().find(|t| t.id == d3_id) {
            t.depends_on = Some(d2_id.clone());
        }
        let ordered = plan.ordered_tasks();
        let idx = |id: &str| ordered.iter().position(|t| t.id == id).unwrap();
        assert!(
            idx(&d1_id) < idx(&d2_id) && idx(&d2_id) < idx(&d3_id),
            "chain must be emitted dependency-first, got order: {:?}",
            ordered.iter().map(|t| &t.id).collect::<Vec<_>>()
        );
    }

    /// C2: a dependency cycle must be broken deterministically (no deadlock,
    /// all tasks emitted exactly once).
    #[test]
    fn test_ordered_tasks_cycle_broken() {
        let a = Task::new("a", AgentType::General, serde_json::json!({}));
        let b = Task::new("b", AgentType::General, serde_json::json!({}));
        let a_id = a.id.clone();
        let b_id = b.id.clone();
        let mut plan = ExecutionPlan::new("cycle", vec![a, b]);
        if let Some(t) = plan.tasks.iter_mut().find(|t| t.id == a_id) {
            t.depends_on = Some(b_id.clone());
        }
        if let Some(t) = plan.tasks.iter_mut().find(|t| t.id == b_id) {
            t.depends_on = Some(a_id.clone());
        }
        let ordered = plan.ordered_tasks();
        assert_eq!(ordered.len(), 2, "both cycle members must be emitted");
        let ids: Vec<&str> = ordered.iter().map(|t| t.id.as_str()).collect();
        assert_eq!(
            ids.iter().filter(|id| **id == a_id.as_str()).count(),
            1,
            "each task emitted exactly once"
        );
    }

    #[test]
    fn test_build_context() {
        let r1 = AgentResult {
            task_id: "t1".to_string(),
            agent_id: "a1".to_string(),
            agent_type: AgentType::General,
            status: TaskStatus::Completed,
            output: serde_json::json!({ "result": 42 }),
            summary: String::new(),
            needs_refinement: false,
            fixable: false,
            suggested_followup: vec![],
            duration_ms: 100,
            completed_at: Some(Utc::now()),
        };
        let ctx = build_context(&[r1]);
        assert_eq!(ctx.get("t1").unwrap().get("result").unwrap(), 42);
    }

    #[test]
    fn test_merge_context_into_input() {
        let input = serde_json::json!({ "action": "write", "path": "test.txt" });
        let context = serde_json::json!({ "parent-task": { "content": "hello" } });
        let merged = merge_context_into_input(&input, &context, &Some("parent-task".to_string()));
        assert_eq!(merged.get("action").unwrap(), "write");
        assert_eq!(merged.get("content").unwrap(), "hello");
    }
}
