use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Unique identifier for an agent instance.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AgentId(pub String);

impl AgentId {
    pub fn new(id: &str) -> Self { Self(id.to_string()) }
    pub fn generate() -> Self {
        Self(format!("agent-{}", Uuid::new_v4()))
    }
}

impl std::fmt::Display for AgentId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// The type/category of a task.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum AgentType {
    Research,
    Coding,
    Implementation,
    General,
}

impl Default for AgentType {
    fn default() -> Self { AgentType::General }
}

impl std::fmt::Display for AgentType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AgentType::Research => write!(f, "research"),
            AgentType::Coding => write!(f, "coding"),
            AgentType::Implementation => write!(f, "implementation"),
            AgentType::General => write!(f, "general"),
        }
    }
}

/// A single unit of work within an execution plan.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Task {
    /// Unique identifier for this task.
    pub id: String,
    /// Human-readable description of what this task does.
    pub description: String,
    /// Agent type best suited for this task.
    pub agent_type: AgentType,
    /// Input data required to execute this task (tool parameters, context, etc.).
    pub input: serde_json::Value,
    /// Optional parent task ID — if set, this task depends on the parent completing first.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<String>,
    /// Maximum number of retry attempts before marking as failed.
    #[serde(default = "default_max_retries")]
    pub max_retries: u32,
    /// Priority ordering (lower number = higher priority).
    #[serde(default = "default_priority")]
    pub priority: u32,
}

fn default_max_retries() -> u32 { 3 }
fn default_priority() -> u32 { 0 }

impl Task {
    pub fn new(description: &str, agent_type: AgentType, input: serde_json::Value) -> Self {
        Self {
            id: format!("task-{}", Uuid::new_v4()),
            description: description.to_string(),
            agent_type,
            input,
            depends_on: None,
            max_retries: default_max_retries(),
            priority: default_priority(),
        }
    }
}

/// A complete plan generated by the Planner and executed by the Supervisor.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ExecutionPlan {
    /// Unique plan identifier.
    pub plan_id: String,
    /// The original user request that this plan addresses.
    pub user_request: String,
    /// All tasks to be executed.
    pub tasks: Vec<Task>,
    /// Timestamp when the plan was created.
    pub created_at: DateTime<Utc>,
    /// Arbitrary metadata (e.g., confidence score, estimated steps).
    #[serde(default)]
    pub metadata: serde_json::Value,
}

impl ExecutionPlan {
    pub fn new(user_request: &str, tasks: Vec<Task>) -> Self {
        Self {
            plan_id: format!("plan-{}", Uuid::new_v4()),
            user_request: user_request.to_string(),
            tasks,
            created_at: Utc::now(),
            metadata: serde_json::Value::Object(serde_json::Map::new()),
        }
    }

    /// Returns tasks in dependency-respecting, priority-ordered sequence.
    pub fn ordered_tasks(&self) -> Vec<&Task> {
        let mut sorted = Vec::new();
        let mut visited = std::collections::HashSet::new();

        fn visit<'a>(
            task: &'a Task,
            all_tasks: &'a [Task],
            visited: &mut std::collections::HashSet<&'a str>,
            sorted: &mut Vec<&'a Task>,
        ) {
            if !visited.insert(&task.id) {
                return;
            }
            if let Some(dep_id) = &task.depends_on {
                if let Some(dep) = all_tasks.iter().find(|t| &t.id == dep_id) {
                    visit(dep, all_tasks, visited, sorted);
                }
            }
            sorted.push(task);
        }

        let mut roots: Vec<&Task> = self
            .tasks
            .iter()
            .filter(|t| t.depends_on.is_none())
            .collect();
        roots.sort_by_key(|t| t.priority);

        for root in roots {
            visit(root, &self.tasks, &mut visited, &mut sorted);
        }

        for task in &self.tasks {
            if visited.insert(&task.id) {
                sorted.push(task);
            }
        }

        sorted
    }

    /// Returns the set of root tasks (no dependencies).
    pub fn root_tasks(&self) -> Vec<&Task> {
        let dep_set: std::collections::HashSet<&str> = self
            .tasks
            .iter()
            .filter_map(|t| t.depends_on.as_deref())
            .collect();
        self.tasks
            .iter()
            .filter(|t| !dep_set.contains(t.id.as_str()))
            .collect()
    }
}

/// The result returned by a Worker Agent after executing a task.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AgentResult {
    pub task_id: String,
    pub agent_id: String,
    pub agent_type: AgentType,
    pub status: TaskStatus,
    /// The output payload (success data, error message, or partial result).
    pub output: serde_json::Value,
    /// Human-readable summary for the feedback loop.
    #[serde(default)]
    pub summary: String,
    /// Whether the Supervisor should ask the Planner to refine the plan.
    #[serde(default)]
    pub needs_refinement: bool,
    /// Follow-up tasks the worker suggests adding.
    #[serde(default)]
    pub suggested_followup: Vec<Task>,
    /// Timing information.
    #[serde(default)]
    pub duration_ms: u64,
    #[serde(default)]
    pub completed_at: Option<DateTime<Utc>>,
}

/// Task execution status.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TaskStatus {
    Pending,
    Running,
    Completed,
    Failed,
    Retryable,
    Cancelled,
}

impl std::fmt::Display for TaskStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TaskStatus::Pending => write!(f, "pending"),
            TaskStatus::Running => write!(f, "running"),
            TaskStatus::Completed => write!(f, "completed"),
            TaskStatus::Failed => write!(f, "failed"),
            TaskStatus::Retryable => write!(f, "retryable"),
            TaskStatus::Cancelled => write!(f, "cancelled"),
        }
    }
}

/// Messages that flow between agents in the feedback loop.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum FeedbackMessage {
    /// Worker reports completion or failure to Supervisor.
    TaskReport { result: AgentResult },
    /// Supervisor asks Planner to refine the plan.
    RequestRefinement {
        completed_tasks: Vec<AgentResult>,
        failed_tasks: Vec<AgentResult>,
        context: serde_json::Value,
    },
    /// Planner returns an updated plan.
    UpdatedPlan { plan: ExecutionPlan },
    /// Supervisor delegates a task to a Worker.
    TaskDelegation { task: Task, context: serde_json::Value },
    /// Planner signals that the overall objective is satisfied.
    ObjectiveComplete { final_output: serde_json::Value },
}

/// Builds a context value from completed task results, keyed by task_id.
pub fn build_context(completed: &[AgentResult]) -> serde_json::Value {
    let mut map = serde_json::Map::new();
    for result in completed {
        map.insert(result.task_id.clone(), result.output.clone());
    }
    serde_json::Value::Object(map)
}

/// Looks up a parent task's output from the context.
pub fn get_parent_output<'a>(context: &'a serde_json::Value, task_id: &str) -> Option<&'a serde_json::Value> {
    context.get(task_id)
}

/// Merges parent task outputs from context into a task's input.
pub fn merge_context_into_input(
    input: &serde_json::Value,
    context: &serde_json::Value,
    depends_on: &Option<String>,
) -> serde_json::Value {
    if let Some(dep_id) = depends_on {
        if let Some(parent_output) = context.get(dep_id) {
            let mut merged = input.clone();
            if let serde_json::Value::Object(mut obj) = merged {
                if let serde_json::Value::Object(parent_obj) = parent_output {
                    for (k, v) in parent_obj {
                        obj.entry(k.clone()).or_insert(v.clone());
                    }
                }
                merged = serde_json::Value::Object(obj);
            }
            merged
        } else {
            input.clone()
        }
    } else {
        input.clone()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_agent_id_generate() {
        let id1 = AgentId::generate();
        let id2 = AgentId::generate();
        assert_ne!(id1, id2);
        assert!(id1.0.starts_with("agent-"));
    }

    #[test]
    fn test_task_new() {
        let task = Task::new("test task", AgentType::General, serde_json::json!({ "query": "hello" }));
        assert_eq!(task.description, "test task");
        assert_eq!(task.agent_type, AgentType::General);
        assert_eq!(task.max_retries, 3);
        assert_eq!(task.priority, 0);
    }

    #[test]
    fn test_execution_plan_ordered_tasks() {
        let t1 = Task::new("first", AgentType::General, serde_json::json!({}));
        let t2 = Task::new("second", AgentType::General, serde_json::json!({}));
        let t3 = Task::new("third (depends on first)", AgentType::Coding, serde_json::json!({})) ;
        let mut plan = ExecutionPlan::new("test", vec![t2, t1, t3]);
        // Set up dependency: t3 depends on t1
        if let Some(task) = plan.tasks.iter_mut().find(|t| t.id == t3.id) {
            task.depends_on = Some(t1.id.clone());
        }
        let ordered = plan.ordered_tasks();
        let ids: Vec<&str> = ordered.iter().map(|t| &t.id[..8]).collect();
        // t1 should come before t3
        let t1_idx = ordered.iter().position(|t| t.id == t1.id).unwrap();
        let t3_idx = ordered.iter().position(|t| t.id == t3.id).unwrap();
        assert!(t1_idx < t3_idx, "dependency t1 should come before t3");
    }

    #[test]
    fn test_build_context() {
        let r1 = AgentResult {
            task_id: "t1".to_string(),
            agent_id: "a1".to_string(),
            agent_type: AgentType::General,
            status: TaskStatus::Completed,
            output: serde_json::json!({ "result": 42 }),
            summary: String::new(),
            needs_refinement: false,
            suggested_followup: vec![],
            duration_ms: 100,
            completed_at: Some(Utc::now()),
        };
        let ctx = build_context(&[r1]);
        assert_eq!(ctx.get("t1").unwrap().get("result").unwrap(), 42);
    }

    #[test]
    fn test_merge_context_into_input() {
        let input = serde_json::json!({ "action": "write", "path": "test.txt" });
        let context = serde_json::json!({ "parent-task": { "content": "hello" } });
        let merged = merge_context_into_input(&input, &context, &Some("parent-task".to_string()));
        assert_eq!(merged.get("action").unwrap(), "write");
        assert_eq!(merged.get("content").unwrap(), "hello");
    }
}
